### ISSUE TITLE
setup.py needs to be run twice to properly copy x393.h

### ISSUE THREAD

**Issue by peacememories** [Elphel/elphel393#1]
When trying to build `linux-xlnx` for the elphel393, I ran into a problem where `x393.h` was not found. Some digging revealed that the rsync-command in `setup.py` doesn't get run on the first script run, because `os.path.isdir(cwd+"/linux-elphel/src/drivers/elphel")` returns `false`.
This means I need to run setup.py twice to properly set up the project.

**Comment by okdzhimiev** [comment]
Fixed.
`setup.py` was reading `projects.json` projects as unordered dict - they were ordered alphabetically by name. 
1. `setup.py` - changed parsing projects into OrderedDict
2. `projects.json` - moved `linux-elphel` above `fpga-elphel` - so it is cloned earlier.
